### ISSUE TITLE
performance of json flattener

### ISSUE THREAD

**Issue by sambitdixit** [wnameless/json-flattener#11]
Have you done any performance benchmark of this son flattener. When we ran it against a high volume json events stream to flatten, its taking significant time. I think it creates a lot of JsonFlatten object and the parser it uses is probably not the fastest.

**Comment by wnameless** [comment]
Really!? Can u provide me the testing dataset?
I would like to do some of the benchmarks.

**Comment by wnameless** [comment]
I just made a rough benchmark:
I flattened 111mb json data in 8sec.

Do you still consider it's slow?

**Comment by javasoze** [comment]
I did a simple benchmark against Jackson.
Using jsonflattener is about 3x slower compare to just ObjectMapper.readValue...

I am not suggesting jsonflattener is slow, just in relative to not having to flatten.

**Comment by wnameless** [comment]
JasonFlattener is based on minimalJSON instead of Jackson due to the better performance. BTW, did you do anything AFTER #readValue? I would like to dig deeper into this issue.

**Comment by javasoze** [comment]
I simply added the size of the map from readValue to a global variable just to avoid the compiler optimizes away my perf loop.

I am not suggesting the existence of a performance issue nor am I implying JsonFlattener is slow. Just providing some data point and context from my analysis.

**Comment by wnameless** [comment]
I see. Thanks to you anyway. You just inspired me that I should add the lazy initialization mechanism in the next release.
