### ISSUE TITLE
grouping according to keys

### ISSUE THREAD

**Issue by information-miner** [wnameless/json-flattener#15]
is there a way such that we can group all the values for a key type into a list ?
for example consider the json below :arrow_down: 

```
{"data":
[
{
    "Name": "crunchify.com",
    "Author": "App Shah",
    "Address": "New York"
},
{
    "Name": "crunchify.com",
    "Author": "App Shah",
    "Address": "New York"
}
]
}
```

the output is :arrow_down: 

```
data[0].Address : New York
data[0].Author : App Shah
data[0].Name : crunchify.com
data[1].Address : New York
data[1].Author : App Shah
data[1].Name : crunchify.com
```

can i group the data into lists such as 

```
Address = [New York , New York]
Author = [App Shah , App shah]
Name = [crunchify.com , crunchify.com]
```

**Comment by wnameless** [comment]
Did you try KEEP_ARRAYS mode?

**Comment by information-miner** [comment]
yes i have tried it but it Keeps the whole array the output is below

`data : [{"Address":"New York","Author":"App Shah","Name":"crunchify.com"},{"Address":"New York","Author":"App Shah","Name":"crunchify.com"}]`

**Comment by wnameless** [comment]
I am still not sure if this feature should be implemented or not?
Let me ask you a question: 
If those nested JSON objects have different key sets(ex: [Address,Author], [Author, Name]), what will be the ideal output in your mind?

**Comment by kamalpradhan95** [comment]
**the expected output will be**
Address = [Address , Null]
Author = [Author , Author]
Name = [Null , Name]
