### ISSUE TITLE
Fail to Flatten Object with Field Key "root"

### ISSUE THREAD

**Issue by 7leafcom** [wnameless/json-flattener#18]
If there is a field called "root" anywhere in the JSON, it will not get flattened properly.

String json = "{\"root\":null}";
String flattened = new JsonFlattener(json).withSeparator('@').withFlattenMode(FlattenMode.KEEP_ARRAYS).flatten();
System.out.println(flattened);

**Comment by wnameless** [comment]
This bug has been fixed in version 0.2.4. Thanks for reporting.
