### ISSUE TITLE
Support Java POJOs and custom map key labels using Annotations

### ISSUE THREAD

**Issue by ashishthukral** [wnameless/json-flattener#19]
Can we add some annotation support for Java pojos to map json keylabels to specific labels ?
e.g.
public class Test{

@ SomeAnnotation("myCustomLabel")
private Integer myField  = 3;
}

JsonFlattener.flatten(new Test());
should produce Map with myCustomLabel, 3

**Comment by wnameless** [comment]
If you want to do this kind of tricks to the POJOs, I would recommand you to use the Jackson Annotations. You can convert any POJO you like with Jackson mapper into plain JSON and then call the JsonFlattener any time you want.

**Comment by ashishthukral** [comment]
the thing is that i am using this on java pojo which already have a jackson annotation with some other keymapping. So i dont want to couple the json naming and flatmap naming together.
