### ISSUE TITLE
Support custom label handling for array indices?

### ISSUE THREAD

**Issue by ashishthukral** [wnameless/json-flattener#20]
Like we have withSeparator for nesting levels, can we have something similar for collection/array indices ?
string json = {key:[1,2,3]};
e.g. jsonflatterer.withInexSeparator('_').flat(json);

key_0 ,1 (instead of key[0] , 1)
key_1 ,2 (instead of key[1] , 2)
key_2 ,3 (instead of key[2] , 3)

**Comment by wnameless** [comment]
Since 0.3.0, it's kind of possible.
