### ISSUE TITLE
JsonUnflattener fail to unflatten flatten string with KEEP_ARRAYS

### ISSUE THREAD

**Issue by nqkdev** [wnameless/json-flattener#26]
Original: {"a":[1,2,3],"b":[{"c":{"d":[1,2]}}]}
Flattened with KEEP_ARRAYS: {"a":[1,2,3],"b":[{"c.d":[1,2]}]}
Unflattened: {"a":[1,2,3],"b":[{"c.d":[1,2]}]}

JsonUnflattener does not unflatten object in the array "b".

**Comment by wnameless** [comment]
The bug has been fixed in version 0.4.1.
