### ISSUE TITLE
Flattener.withSeparator breaking when nested JSON key has separator char in it.

### ISSUE THREAD

**Issue by arvind-kalyan** [wnameless/json-flattener#28]
Hi, 

I was trying out the withSeparator functionality, turns out that it doesn't work correctly for few cases. **Whenever we're using a separator and the nested JSON key has that separator, it breaks.**

Eg. withSeparator('_')

Eg. {"a": 45, "b": {"c": "val"}}; // works fine in this case.
Output: {"a": 45, "b_c": "val"}

Eg. {"a": 45, "b": {"c_type": "val"}}  // breaks since nested field c_type has an _ in it.
Output: {"a":45,"b[\"c_type\"]":"val"}

This is the case whenever the separator char is present in one of the field key.

**Comment by arvind-kalyan** [comment]
@wnameless - When I have some time in the weekend, I can work on this and submit a PR. Good to go?

**Comment by wnameless** [comment]
The KeyTransformer should help somehow.

**Comment by arvind-kalyan** [comment]
Hi @wnameless - I still want "_" in the key, so can't transform it.

**Comment by wnameless** [comment]
I just reviewed your question again. In my opinion, the result of 2nd case is totally correct. What's your expectation in this case?

**Comment by arvind-kalyan** [comment]
Hi @wnameless, Expected output is {"a":45,"b.c_type":"val"}.

**Comment by wnameless** [comment]
It's not logical. You just declared "_" as the separator. How can you expect "." to be the separator again. BTW, putting key which contains separator character in brackets are the convention way to deal with this kind of problems. Please see the Readme.md first.

**Comment by arvind-kalyan** [comment]
Hey @wnameless - My bad, Expected output is {"a":45,"b_c_type":"val"}. Is there some workaround to get it in the above format? This is a pre-condition for the use case I'm looking at. Do let me know.

Thanks.

**Comment by wnameless** [comment]
For now, there is no solution to your case. Allowing "b_c_type" to be a key will cause more problems during unflattening. You can try the FlattenMode.MONGO which behaves almost the way you want, but it's still not allow separator character to be shown in the key. However you can combine it with KeyTransformer to customize the outcome.
