### ISSUE TITLE
Flattening the parent object

### ISSUE THREAD

**Issue by tarkal** [wnameless/json-flattener#29]
When flattening a model is it currently possible to provide an object parent level entry with the flattened object as the value?

So for an model like this:
```
{
  "object": {
    "id": 123,
    "name": "example"
  }
}
```

you get:

```
object             ->  { "id": 123, "name": "example" }
object.id          -> 123
object.name        -> "example"
```

Given that the intent is to flatten the model it would also be useful to be able to specify whether to convert it to a string.

```
object             ->  "{ \"id\": 123, \"name\": \"example\" }"
object.id          -> 123
object.name        -> "example"
```

**Comment by wnameless** [comment]
For now it's not possible. However is's quiet east to be done with few lines of code.
For example:
Map<String, Object> m = JsonFlattener.flattenAsMap(json);
m.add("object", JsonFlattener.flattenAsMap(json));

Map m is what you want and there are plenty of tools can help you convert a Map into JSON, ex: GSON.

For your second request, I would suggest you to use StringEscapeUtils in Apache Common Lang.
