### ISSUE TITLE
Issue with empty json array .

### ISSUE THREAD

**Issue by jamsheer-citrus** [wnameless/json-flattener#3]
While do the flatten this library removing empty json array if our input  contain empty valued json array .So we are getting miss match data if we compare un flattened data with actual input .

**Comment by wnameless** [comment]
Can you provide me an example?
I would like to solve this ASAP.

jamsheer <notifications@github.com> 於 2016年1月19日週二 20:45 寫道：

**Comment by jamsheer-citrus** [comment]
{
	"no": "1",
	"name": "riya",
	"marks": []
}


Please try with this json

**Comment by wnameless** [comment]
I just fixed it. Please try it again with version 0.1.2.

**Comment by jamsheer-citrus** [comment]
Its working  now,Thank you
