### ISSUE TITLE
Denormalizing the Child with immediate parent 

### ISSUE THREAD

**Issue by ssabnis** [wnameless/json-flattener#30]
For example,

Input JSON - { "a": { "b": 1, "c": null, "d": [false, true] }, "e": "f", "g": 2.3 }
Flattened JSON -  { "a.b": 1, "a.c": null, "a.d[0]": false, "a.d[1]": true, "e": "f", "g": 2.3 }
 
Is it possible to convert the above input JSON into the following structure ? 
 
{"a.b": 1, "a:c": null, "e": "f", "g": 2.3}
{"a.b": 1, "a:c": null, "e": "f", "g": 2.3, "a.d": false}
{"a.b": 1, "a:c": null, "e": "f", "g": 2.3, "a.d": true}

**Comment by wnameless** [comment]
It's not possible for now. BTW, the time complexity in your case will be increased tremendously if the number of nested arrays is large. I am also curious why you need this kind of outcome?
