### ISSUE TITLE
Using '_' as a separator results in malformed result.

### ISSUE THREAD

**Issue by john-pondr** [wnameless/json-flattener#32]
Input  = "{\"bean\":{\"hostname\":\"e46e98985\",\"name\":\"898898de5\",\"version\":\"5.5\"},\"input_type\":\"log\",\"message\":{\"sensor_id\":\"p02\",\"ts\":1.519776762821703E9,\"uid\":\"CVfeCHDFIFIfXSTcj\",\"id_orig_h\":\"10.10.10.10\"

output = {"bean_hostname":"e46e98985","bean_name":"e46e98985","bean_version":"5.5","`[\"input_type\"]`:"log",`"message[\"sensor_id\"]":"p02"`,"message_ts":1519776762.821703,"message_uid":"CVfeCHDFIFIfXSTcj\",`"message[\"id_orig_h\"]"`:"10.10.10.10",

It looks like values with '_ ' characters throw off the parser and it escapes the value and wraps it in brackets.  

Any ideas on how to fix this. I tried a few other characters and they work fine.

**Comment by wnameless** [comment]
It is not a bug. It is exactly how the JsonFlattener works. If there is any key contains the character which is used by the separator, it will wrap the keys it in brackets.

It is also how JavaScript handles such problem: [https://stackoverflow.com/questions/2577172/how-to-get-json-objects-value-if-its-name-contains-dots](url).

If you don't want the default behavior, you can use the KeyTransfomer to modify the outcome you wish to see.

**Comment by john-pondr** [comment]
Thanks for the explanation. I had determined it was due to the key names containing the same character. Overall I love the library.
