### ISSUE TITLE
Slash in json value will prefix backslash after flatten 

### ISSUE THREAD

**Issue by yjhyjhyjh0** [wnameless/json-flattener#33]
It's nice to have json flatten library.
Just notice that Apache NiFi 'FlattenJson' processor utilize this library to flat json.

Recently I've been working on some features update on this processor.
I noticed that if there is a slash at input json value.
Output will prefix every slash with a backslash .

For example,
input text:
{"innerClass":{},"col3":["http://localhost:8080/test1","http://localhost:8080/test2"]}
output text in dot notation:
{"innerClass":{},"col3[0]":"http:\/\/localhost:8080\/test1","col3[1]":"http:\/\/localhost:8080\/test2"}
(Message didn't show precisely in this text dialog there is actually backslash exist before slash)

Not sure if it's expected behavior.
But to me, it looks like data un-match problem.
This happens to all 3 flatten mode.

Please let me know your feedback.
Thanks.

**Comment by wnameless** [comment]
What a coincident! I just made an update to this library today, and I added a new interface called CharSequenceTranslatorFactory, which can be used by JsonFlattener#withStringEscapePolicy, to this library which allows user to provide their own escape policy. In your situation, you just have to implement CharSequenceTranslatorFactory and return StringEscapeUtils.ESCAPE_JAVA in this @FuntionalInterface; I believed it will solve your problem. Please let me know if you have any question.

**Comment by yjhyjhyjh0** [comment]
Wow indeed there's new version today.
I'll have a try and report result here.

Thanks a lot for the quick reply.

**Comment by yjhyjhyjh0** [comment]
It works out very well as you mentioned.

I'll try to update this solution to Apache NiFi.
Really appreciate your help.
