### ISSUE TITLE
Forward slash in json key gets escaped on conversion

### ISSUE THREAD

**Issue by mayankpahwa** [wnameless/json-flattener#37]
Hi,

I am using this library to flatten a nested json and it is very useful. I have one minor issue when the JSON key contains a forward slash, i.e. `/`.

For ex: `"{\"user/id\":123}"` on flattening becomes `"{\"user\\/id\":123}"`. 

Is there a way to prevent this and retain the actual key in the final output.

Thanks,
Mayank

**Comment by wnameless** [comment]
Yes, there is an approach to get the output you want.
You can provide your own  StringEscapePolicy by implementing the CharSequenceTranslatorFactory.

For example:

 new JsonFlattener("{\"key\": \"value\"}")
        .withStringEscapePolicy(new CharSequenceTranslatorFactory() {

          @Override
          public CharSequenceTranslator getCharSequenceTranslator() {
            return new AggregateTranslator(
                new LookupTranslator(new HashMap<CharSequence, CharSequence>() {
                  private static final long serialVersionUID = 1L;
                  {
                    put("\"", "\\\"");
                    put("\\", "\\\\");
                    // put("/", "\\/"); Make this line as a comment
                  }
                }), new LookupTranslator(EntityArrays.JAVA_CTRL_CHARS_ESCAPE));
          }

        });

**Comment by wnameless** [comment]
You can try version 0.6.0. The default escape policy is exactly what you want.
