### ISSUE TITLE
array of objects does not support same key

### ISSUE THREAD

**Issue by mpet** [wnameless/json-flattener#38]
String json = "{ \"measurements\" : { \"name\" : \"fromState\", \"value\": \"AB\", \"name\" : \"toState\",\"value\": \"BC\"}}";
        String flattenedJson = JsonFlattener.flatten(json);

Gives:

{"measurements.name":"toState","measurements.value":"BC"}

I expected to have both values included.

//mike

**Comment by wnameless** [comment]
Actually it is not array of objects here and JSON objects are not allowed same key used twice.
If you really want to keep different values with the same key, you should do some like this:
[{ "name" : "fromState", "value": "AB"}, {"name" : "toState", "value": "BC"}]
