### ISSUE TITLE
What is the key to search for when there is a period in the key?

### ISSUE THREAD

**Issue by AshishHNP** [wnameless/json-flattener#39]
I saw the EscapePolicy updates, but not sure if I am understanding it correctly.

If I have a json that looks something like

{
"test.v1": {
"_id": "test.v1"
}
}

On a flattenedJson where I have a Map<String, Object>
I would expect to be able to do something like

"test\.v1._id" and value would be test.v1
In my logging of the set of keys though I see it wrapped in something else:

[\"test.v1\"]._id is what the actual key is. How does this map to what I should be writing in String

Thanks

**Comment by wnameless** [comment]
Because your key contains the separator(.), ["test.v1"] is the default behavior to escape the separator in the key.
