### ISSUE TITLE
Issue in unflattening json

### ISSUE THREAD

**Issue by prabitharp** [wnameless/json-flattener#4]
Issue while unflattening Json data: 

When I tried this Json to unflatten using unflattening library,
it produces the following error : 

Exception in thread "main" java.lang.UnsupportedOperationException:
 Not an object: null

{
"course.List[5].type":"B",
"course.List[1].type":"C"
}

**Comment by wnameless** [comment]
I guess this is what you tried to do:

{
"course.List[0].type":null,
"course.List[1].type":"C",
"course.List[2].type":null,
"course.List[3].type":null,
"course.List[4].type":null,
"course.List[5].type":"B"
}

Am I right?

BTW, JsonUnflattener is not designed to unflatten an arbitrary json at first place; it was only designed to unflatten a json which is been flattened by the JsonFlattener.

Hope this solve your question.

**Comment by prabitharp** [comment]
Our issue is with unflattening json. If we try to unflatten as the order mentioned
below as the 5th array first it will automatically assign the other elements 
as null

{
	"course.List[5].type":"B",
	"course.List[4].type":"B",
	"course.List[2].type":"B",
	"course.List[3].type":"B",
	"course.List[1].type":"C",
	"course.List[0].type":"B"
}

If I tried this I get the same issue

java.lang.UnsupportedOperationException: Not an object: null
	
It work fine with http://fiddle.jshell.net/blowsie/S2hsS/show/light/

**Comment by wnameless** [comment]
The bug has been fixed in version 0.1.3. Thanks for reporting.

**Comment by prabitharp** [comment]
Thanks for considering this issue. It works fine.
