### ISSUE TITLE
Left and right bracket really have to be different?

### ISSUE THREAD

**Issue by ioah86** [wnameless/json-flattener#40]
Hi! Love your lib, it is really useful.

However, there is one thing: If I try the following, I get an error that the brackets are not allowed to be the same symbol
```scala
new JsonFlattener(line)
  .withLeftAndRightBrackets('#', '#')
  .withSeparator('_')
  .flattenAsMap()
```
Why is that? I can think of the brackets being the same character, which is just denoting some sort of separator.

It would be great if this could be supported in the next version, unless something speaks against it.

**Comment by wnameless** [comment]
Can the FlattenMode.MONGODB solve your problem?
