### ISSUE TITLE
 com.github.wnameless.json.flattener.JsonFlattener.jsonVal2Obj with double value as 0.0

### ISSUE THREAD

**Issue by manishk1683** [wnameless/json-flattener#50]
Hi,
Below method is throwing number format Exception if the json value is "0.0" during jsonValue.asLong();

  private Object jsonVal2Obj(JsonValue jsonValue) {
    if (jsonValue.isBoolean()) return jsonValue.asBoolean();
    if (jsonValue.isString()) return jsonValue.asString();
    if (jsonValue.isNumber()) {
      double v = jsonValue.asDouble();
      if (!Double.isNaN(v) && !Double.isInfinite(v) && v == Math.rint(v))
        return jsonValue.asLong();
      else
        return jsonValue.asDouble();
    }

    return null;
  }

**Comment by wnameless** [comment]
This method has been changed in the newest version 0.9.0. Have you tried it?
