### ISSUE TITLE
Add support for nested objects unflattening with null container

### ISSUE THREAD

**Issue by gscaparrotti** [wnameless/json-flattener#51]
I noticed that it is currently impossible to unflatten the following JSON:

```
"outer": null,
	"outer.inner": null
```

the outer object is `null`, so the following exception is thrown: ` java.lang.ClassCastException: class com.fasterxml.jackson.databind.node.NullNode cannot be cast to class com.fasterxml.jackson.databind.node.ObjectNode`.

Obviously, the `"outer.inner": null` part has been added after the flattening process. I know that the unflattening feature isn't intended to be used with arbitrary JSONs, but there are circumstances where it would be useful (in my case, I'd like to add a nested object to a flattened JSON I receive, which sometimes lacks the outer object).

**Comment by wnameless** [comment]
Sorry, I feel it compromises the concept of JSON unflattener, so I don't have the plan to implement it in the near future.
