### ISSUE TITLE
[Bug] flattenAsMap produces escaped field names for field names that contain dot

### ISSUE THREAD

**Issue by slisaasquatch** [wnameless/json-flattener#52]
Here's a code sample to demonstrate the issue.

```java
public static void main(String[] args) throws Exception {
	final ObjectMapper mapper = new ObjectMapper();
	/*
	 * The input is just a simple json object { "a.b": 1 }
	 */
	final String jsonString = "{ \"a.b\": 1 }";
	final String flattenedString = JsonFlattener.flatten(jsonString);
	/*
	 * The following line prints
	 * {"[\"a.b\"]":1}
	 *
	 * No problem here.
	 */
	System.out.println(flattenedString);
	/*
	 * Print the only field name in the flattened json. It prints
	 * ["a.b"]
	 *
	 * No problem here either.
	 */
	System.out.println(mapper.readTree(flattenedString).fieldNames().next());
	final Map<String, Object> flattenedMap = JsonFlattener.flattenAsMap(jsonString);
	/*
	 * Print the only field name in the flattened map. It prints
	 * [\"a.b\"]
	 *
	 * And here's the problem. For some reason the quotes in the field name in the
	 * flattened map got unnecessarily escaped.
	 */
	System.out.println(flattenedMap.keySet().iterator().next());
	/*
	 * Just to confirm this, I'm parsing the map into json and printing the json.
	 * It prints
	 * {"[\\\"a.b\\\"]":1}
	 *
	 * So yes, the flattened map field name got unnecessarily escaped
	 */
	System.out.println(mapper.writeValueAsString(mapper.valueToTree(flattenedMap)));
}
```

So the gist of the issue is that, when you have a field name with a dot, the `flatten` method flattens things correctly, but `flattenAsMap` produces a `Map` with field names that got unnecessarily (and incorrectly) escaped.

**Comment by wnameless** [comment]
You may use the following example to avoid dot(.) escaping:

new JsonUnflattener(json).withSeparator('*').unflatten()

**Comment by slisaasquatch** [comment]
* The issue is for `JsonFlattener`, not `JsonUnflattener`.
* I don't want to avoid dot escaping. The issue is that `JsonFlattener`'s `flattenAsMap` method double escapes quotes(`"`) if the field name contains dots.
* The `flatten` method of `JsonFlattener` works correctly.

This issue is easy to work around, because the `flatten` method does work correctly. However, this is still clearly a bug in my opinion.

**Comment by slisaasquatch** [comment]
Just in case my original example is not readable enough.

Given this simple JSON object: `{ "a.b": 1 }`.

If you try to flatten it with `JsonFlattener.flatten`, it produces `{"[\"a.b\"]":1}` as expected.

If you try to flatten it with `JsonFlattener.flattenAsMap` however, it produces `{"[\\\"a.b\\\"]":1}`.

**Comment by wnameless** [comment]
I ran following codes with v0.9.0:

    String json = "{ \"a.b\": 1 }";
    System.out.println(JsonFlattener.flatten(json));
    System.out.println(JsonFlattener.flattenAsMap(json));

And I got:
{"[\"a.b\"]":1}
{"[\"a.b\"]":1}

Did you try it with the newest version?

**Comment by slisaasquatch** [comment]
The version I tried originally was 0.8.1. I just gave 0.9.0 a try, and the issue persists.

But I did figure out why your code sample doesn't exhibit the same issue. What I found is that the `Map` produced by `flattenAsMap` will produce the correct result if you call `toString()` on it. So try getting its `keySet()` like I did in my original example, and you'll see that the key is actually inconsistent with the `toString()` result.

**Comment by wnameless** [comment]
As I mentioned before, you should use either:

 new JsonFlattener(jsonString).withSeparator('*').flatten();
 new JsonFlattener(jsonString).withSeparator('*').flattenAsMap();

to avoid such behavior.

**Comment by slisaasquatch** [comment]
But using `new JsonFlattener(jsonString).withSeparator('*').flatten();` on `{ \"a.b\": 1 }"` produces `{"a.b":1}`, and that's not what I want, and that's not the issue I'm having.

I want the result to be `{"[\"a.b\"]":1}`, and `JsonFlattener.flatten(jsonString);` gives me that.

The issue I'm having is the `flattenAsMap` method. If you call `toString()` on the `Map` produced by `flattenAsMap`, you get `{"[\"a.b\"]":1}`, which is the correct result, and that's essentially what you did in [this example](https://github.com/wnameless/json-flattener/issues/52#issuecomment-711021657). But if you look at the actual keys of the `Map` by calling `keySet()`, you'll see that the only key of the `Map` is `[\"a.b\"]`, while in reality it should be `["a.b"]`. And that's the issue I'm having.

**Comment by slisaasquatch** [comment]
So I'll try to make this simpler.

Given this simple JSON object: `{ "[\"a.b\"]": 1 }`

If we want to represent this JSON object as a `Map`, we do something like this, correct?
```java
final Map<String, Object> m = new HashMap<>();
m.put("[\"a.b\"]", 1);
```
And just to make sure it's correct, I tried printing the JSON representation out with Jackson `ObjectMapper` like this:
```java
System.out.println(mapper.writeValueAsString(m));
```
And it prints `{"[\"a.b\"]":1}`, which is what we expect.

And let's see what the only key of the `Map` is by doing this:
```java
System.out.println(m.keySet().iterator().next());
```
And it prints `["a.b"]`.

Here's the complete code sample:
```java
final ObjectMapper mapper = new ObjectMapper();
final Map<String, Object> m = new HashMap<>();
m.put("[\"a.b\"]", 1);
System.out.println(mapper.writeValueAsString(m)); // prints {"[\"a.b\"]":1}
System.out.println(m.keySet().iterator().next()); // prints ["a.b"]
```

And if you do the same thing to the `Map` produced by `flattenAsMap` like this `System.out.println(m.keySet().iterator().next());`, will print `[\"a.b\"]`, which is wrong. If you call `toString()` on the `Map`, however, it indeed produces valid JSON, which is what gave you the impression [here](https://github.com/wnameless/json-flattener/issues/52#issuecomment-711021657) that `flattenAsMap` produces correct results.

**Comment by wnameless** [comment]
To make it simple for my design philosophy of this lib, I believe 2 things:

1. JSON is not equal to javascript object
2. Java string literal is not equal to Java String object

And these conduct following results:
"[\"a.b\"]" is a JSON string
"[\"a.b\"]"  is also a Java string literal
["a.b"] is the content of a Java String object
["a.b"]  is  the content of a javascript string

Now what you are asking for is to convert  the content of a Java String object as the same as a JSON string, but it is totally not what this library I design to achieve.

If you really want that behavior you wish, just executes the following code:

 CharSequenceTranslator translator =
        StringEscapePolicy.DEFAULT.getCharSequenceTranslator();
    Map<String, Object> newMap = m.entrySet().stream().collect(
        Collectors.toMap(e -> '"' + translator.translate(e.getKey()) + '"',
            Map.Entry::getValue));
    System.out.println(newMap.keySet());

**Comment by zubair-farooqui** [comment]
@wnameless I am facing a similar issue.  Consider following JSON:
`{
	"test": 1,
	"west.": 2
}` 
When we apply `flattenAsMap` on the above JSON then the MAP which is created is like:
![image](https://user-images.githubusercontent.com/12321796/96991353-be9dc400-1541-11eb-9e35-0844c2b40716.png)

If there is a dot (".") in the key then an additional "[\"\"]" is added to the key.  The key "west." becomes [\"west.\"] which is wrong.

**Comment by slisaasquatch** [comment]
@wnameless Yeah this issue imo is very easy to work around, since the `flatten` method produces the correct result, so does `flattenAsMap().toString()`. The problem to me is that because of this issue, the `flattenAsMap` method is basically rendered useless, because I have to call `toString()` on the `Map` to get the correct result and I cannot actually rely on the actual content of the `Map`. If this is expected behavior, I think it is at least worth documenting in Javadoc.

**Comment by wnameless** [comment]
Hi @zubair-farooqui 

Dot(.) is a reserved word which is used to be separators in keys of the flattened JSON. If you wan to change the default separator setting, you simply apply #withSeparator('*') (you can change * to any character you want to use) to either JsonFlattener or JsonUnflattener, in doing so, your problem should be solved.

**Comment by wnameless** [comment]
Hi @slisaasquatch 

A new version 0.10.0 has been released.
I slightly changed the flattenAsMap behavior based on your proposal.
You can give it a try now.

**Comment by slisaasquatch** [comment]
I just gave 0.10.0 a try and the issue seems to have been resolved. Thanks a lot for the quick turnaround!

**Comment by jpomykala** [comment]
Given JSON
```
{
                    "login": {
                        "page": {
                            "name": {
                                "first": "first name",
                                "last": "last name"
                            },
                            "address" : {
                                "line_1": "Login page address line_1",
                                "line_2": "Login page address line_2"
                            }
                        }
                    }
                }
```

```
Map<String, Object> flattenJson = new JsonFlattener(json).withSeparator('.').flattenAsMap();
```

Result
```
Expecting:
  <["["login.me"]["page.line_2"]"]>
to contain exactly in any order:
  <["login.me.page.line_2"]>
elements not found:
  <["login.me.page.line_2"]>
and elements not expected:
  <["["login.me"]["page.line_2"]"]>
```

So how I can get just `login.me.page.line_2` as a key?

**Comment by slisaasquatch** [comment]
@jpomykala I think you must be doing something wrong with your JSON input. Here's my code sample and it does give me the correct result:

```java
public static void main(String[] args) {
	final String jsonStr = "{\n" +
			"                    \"login\": {\n" +
			"                        \"page\": {\n" +
			"                            \"name\": {\n" +
			"                                \"first\": \"first name\",\n" +
			"                                \"last\": \"last name\"\n" +
			"                            },\n" +
			"                            \"address\" : {\n" +
			"                                \"line_1\": \"Login page address line_1\",\n" +
			"                                \"line_2\": \"Login page address line_2\"\n" +
			"                            }\n" +
			"                        }\n" +
			"                    }\n" +
			"                }";
	final Map<String, Object> m = new JsonFlattener(jsonStr).withSeparator('.').flattenAsMap();
	System.out.println(m);
	// prints {"login.page.name.first":"first name","login.page.name.last":"last name","login.page.address.line_1":"Login page address line_1","login.page.address.line_2":"Login page address line_2"}
	System.out.println(m.keySet());
	// prints [login.page.name.first, login.page.name.last, login.page.address.line_1, login.page.address.line_2]
}
```

**Comment by jpomykala** [comment]
Hey @slisaasquatch thanks for the quick response. I realized I used the wrong JSON. I edited my previous comment.

For JSON 
```
{
      {
          "login.me": {
              "page.line_2": "Login page address line_2"
              }
          }
}
```

I'm getting 
```
["login.me"]["page.line_2"]
```
instead
```
login.me.page.line_2
```

I'm using option `withSeparator('.')`
```
Map<String, Object> flattenJson = new JsonFlattener(json).withSeparator('.').flattenAsMap();
```

**Comment by slisaasquatch** [comment]
The default separator is already `'.'`, so setting the separator to that is redundant.

Also, I think producing `["login.me"]["page.line_2"]` is the expected behavior. If the input JSON was flattened to `login.me.page.line_2`, then there would be no way of unflattening it back to `{"login.me":{"page.line_2":"Login page address line_2"}}`.

**Comment by jpomykala** [comment]
Yes, I agree with that. But I don't have plans to unflatten that JSON back :) It would be cool to add options to do such an option. So far my idea to overcome this is to use 
```
Map<String, Object> flattenJson = new JsonFlattener(json).withSeparator('£').flattenAsMap();
```
and then use 
```
jsonKey = jsonKey.replaceAll("£", ".");
```
😄
