### ISSUE TITLE
时间戳转换问题

### ISSUE THREAD

**Issue by 219liangyi** [wnameless/json-flattener#57]
时间戳通过转换之后变成了double类型，而不是long类型。

**Comment by 219liangyi** [comment]
JsonUnflattener.unflatten(eventJson);  这个方法会导致变成double

**Comment by 219liangyi** [comment]
metadata.eventCreationTime":1606896432000
"eventCreationTime":1.606896432E+12

**Comment by wnameless** [comment]
The value '1.606896432E+12' is just a scientific notation and it is not a double number.
