### ISSUE TITLE
Large decimal values getting truncated

### ISSUE THREAD

**Issue by ramkumar-mn** [wnameless/json-flattener#58]
While flattening/unflattening, large decimal values are getting truncated.

**Input:** 
```
{
  "a": 45864.5627834612431243679871256799564,
  "b": -0.0123194,
  "c": 0.00615995
}
```

**Output :**
```
{
  "a": 45864.562783461246,
  "b": -0.0123194,
  "c": 0.00615995
}
```
Here `a` value is getting truncated. But the expected outcome should be same as input.
This can be avoided by setting `DeserializationFeature.USE_BIG_DECIMAL_FOR_FLOATS` in ObjectMapper.
Since there is no option available now, any other workaround possible

**Comment by wnameless** [comment]
There is actually a workaround here:

```java
String json="{\n"
    + "  \"a\": 45864.5627834612431243679871256799564,\n"
    + "  \"b\": -0.0123194,\n"
    + "  \"c\": 0.00615995\n"
    + "}";

ObjectMapper mapper = new ObjectMapper() {
     private static final long serialVersionUID = 1L;
     {
       configure(DeserializationFeature.USE_BIG_DECIMAL_FOR_FLOATS, true);
       configure(DeserializationFeature.USE_BIG_INTEGER_FOR_INTS, true);
     }
   };
```
```java
// Flattener:
JsonNode jn = mapper.readTree(json);
String flattened = JsonFlattener.flatten(new JacksonJsonValue(jn));
```
```java
// Unflattener:
Map<String, ?> map =
        mapper.readValue(json, new TypeReference<Map<String, ?>>() {});
String unflattened = JsonUnflattener.unflatten(map);
```

**Comment by wnameless** [comment]
Since v0.12.0, new JsonCore is applied to this library. You can now change the internal JSON implementation from Jackson to GSON as well. Please read the new features section in the README.md.

Merry Xmas!
