### ISSUE TITLE
Option to not flatten arrays

### ISSUE THREAD

**Issue by mcandre** [wnameless/json-flattener#6]
My use case wants to flatten the keys, but keep all values as they are. Could you please offer a configuration option to keep array values under the same key?

**Comment by wnameless** [comment]
What if those arrays contain other JSON objects?
What is the ideal behaviour to deal with this situation in your mind now?

**Comment by mcandre** [comment]
To reiterate, my use case is flattening only the keys, not the values.

As a workaround, I'm manually identifying keys with `[i]` and patching them back together :/

**Comment by wnameless** [comment]
To clarify:

Original:    { "aaa": [123], "bbb": { "ccc": [456, 789] } }
Flattened: { "aaa": [123], "bbb.ccc": [456, 789] }

Is this what you wish for?

**Comment by mcandre** [comment]
Not quite.

I want all keys flattened, but all values (including arrays) kept the same.

**Comment by jaimelive** [comment]
An option to enable the type of flattening described by the example

Original: { "aaa": [123], "bbb": { "ccc": [456, 789] } }
Flattened: { "aaa": [123], "bbb.ccc": [456, 789] }

Would be ideal, concatenating nested blocks, but keeping arrays.
For disambiguation, 
Original: {"a":[1,2,3],"b":[{"c":{"d":[1,2]}}]}
Flatend: {"a":[1,2,3],"b":[{"c.d":[1,2]}]}

**Comment by jaimelive** [comment]
Pull request sent;
#8

**Comment by wnameless** [comment]
Since v0.2.0, there is an option to keep arrays. Take a try!

**Comment by Xus4** [comment]
very useful to me ,that's what i want
