### ISSUE TITLE
ASCII control characters are not properly escaped

### ISSUE THREAD

**Issue by slisaasquatch** [wnameless/json-flattener#60]
Here's the code example that demonstrates the issue.

```java
public static void main(String[] args) throws Exception {
	final ObjectMapper mapper = new ObjectMapper();
	final char ctrlChar = 16;
	final ObjectNode obj = mapper.createObjectNode().put("test", Character.toString(ctrlChar));
	System.out.println(mapper.writeValueAsString(obj)); // prints {"test":"\u0010"}
	final String flattenedString = JsonFlattener.flatten(new JacksonJsonValue(obj));
	/*
	The line above can be replaced with this and the result will be the same
	final String flattenedString = JsonFlattener.flatten(mapper.writeValueAsString(obj));
	 */
	System.out.println(flattenedString); // prints {"test":""}
	mapper.readTree(flattenedString); // Cannot be parsed. Throws JsonParseException.
}
```

The gist of it is that if the JSON to be flattened has a `String` containing [ASCII control characters](http://ascii-table.com/control-chars.php), the result won't be properly escaped, and the result can't be parsed by Jackson.

Here's the stack trace of the exception thrown at the `mapper.readTree` line.
```java
Exception in thread "main" com.fasterxml.jackson.core.JsonParseException: Illegal unquoted character ((CTRL-CHAR, code 16)): has to be escaped using backslash to be included in string value
 at [Source: (String)"{"test":""}"; line: 1, column: 11]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2337)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:710)
	at com.fasterxml.jackson.core.base.ParserBase._throwUnquotedSpace(ParserBase.java:1094)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._finishString2(ReaderBasedJsonParser.java:2103)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._finishString(ReaderBasedJsonParser.java:2074)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.getText(ReaderBasedJsonParser.java:299)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:69)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:16)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4635)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3042)
	at test.Test.main(Test.java:85)
```

**Comment by wnameless** [comment]
Please use following codes instead:
JsonFlattener jf = new JsonFlattener(new JacksonJsonValue(obj));
jf.withStringEscapePolicy(StringEscapePolicy.ALL);

**Comment by slisaasquatch** [comment]
Thanks for the reply. That indeed works, but this is still a bug, isn't it? Because the original JSON I supplied already has that control character properly escaped and doesn't actually contain that control character at all, i.e. the JSON I supplied is this `{"test":"\u0010"}`, but the library turned it into this `{"test":"�"}`.

**Comment by wnameless** [comment]
Java uses UTF-16 to represent String or Character internally, so the following line of code:
`Character.toString(ctrlChar)` actually produced a UTF-16 character.

However, the next line of code:
`System.out.println(mapper.writeValueAsString(obj))`
For the reason that prints `{"test":"\u0010"}` is the default setting in ObjectMapper.
You can change this behavior by provide a custom module for the ObjectMapper, BTW it's another story.

If you check the [JSON specification](https://tools.ietf.org/html/rfc8259#section-7), you can find out that ASCII code 16(decimal) is not required to be escaped.

Hope this helps somehow.

**Comment by slisaasquatch** [comment]
So if you look at my original example, it says `The line above can be replaced with this and the result will be the same`. So the issue is still present when Jackson isn't involved.

So let me make the example simpler:

```java
public static void main(String[] args) throws Exception {
	final String jsonString = "{\"test\":\"\\u0010\"}";
	System.out.println(jsonString); // prints {"test":"\u0010"}
	final String flattenedString = JsonFlattener.flatten(jsonString);
	System.out.println(flattenedString); // prints {"test":""}
}
```

This time, the input JSON string definitely does NOT have that ASCII control character, but the library still turned `{"test":"\u0010"}` into `prints {"test":""}`, which should not be the expected behavior.

**Comment by wnameless** [comment]
Even though you didn't use Jackson to manipulate any of these inputs, the current default json library inside JsonFlattener is still Jackson.

The input JSON will be unescaped by Jackson as default behavior.

So their are 2 ways you can do to make it as you wish to be. One is to provide a custom Json Core to the JsonFlattener and the other is to set up the StringEscapePolicy.

**Comment by slisaasquatch** [comment]
Yes, I'm fully aware that the library uses Jackson by default behind the scenes, and I actually have a simpler fix:

```java
public static void main(String[] args) throws Exception {
	final ObjectMapper mapper = new ObjectMapper();
	final String jsonString = "{\"test\":\"\\u0010\"}";
	System.out.println(jsonString); // prints {"test":"\u0010"}
	final Map<String, Object> flattenedMap = JsonFlattener.flattenAsMap(jsonString);
	System.out.println(flattenedMap); // prints {"test":""}
	final JsonNode flattenedJson = mapper.valueToTree(flattenedMap);
	System.out.println(mapper.writeValueAsString(flattenedJson)); // prints {"test":"\u0010"}
}
```

I just think the default behavior is surprising and less than desirable. I know the technical reasons behind it, but I think a library like this should keep the input JSON values intact, i.e. if `{"test":"�"}` is provided, then `{"test":"�"}` should be returned, and if `{"test":"\u0010"}` is provided, then `{"test":"\u0010"}` should be returned.

**Comment by wnameless** [comment]
I understand your point of view. I will keep it in my mind. Thx.
