### ISSUE TITLE
Feature request: JsonFlattener flatten to Map<String, String>

### ISSUE THREAD

**Issue by Furytron** [wnameless/json-flattener#61]
Hi, 

I couldn't see if this was already possible in this library, but I have a specific use case where it would be great to flatten JSON as a `Map<String, String>`. This would involve calling the `toString()` method on each of the objects that are returned, since casting would cause a `ClassCastException` for `BigDecimal` variables.

Something like the below would be ideal:
```
Map<String, String> flattenJson = JsonFlattener.flattenAsMap(json, String.class);
Map<String, String> flattenJson = JsonFlattener.flattenAsStringMap(json);
```

At the moment, I need to do something like the following, where I need to convert the values to a String after flattening it.
```
public Map<String, String> flattenJson (String json) {
	Map<String, String> flattenedJsonMap = stringifyMapValues (JsonFlattener.flattenAsMap (json));
	return flattenedJsonMap;
}
public static Map<String, String> stringifyMapValues (Map<String, Object> map) {
	return map.entrySet ().stream ().collect (Collectors.toMap (Map.Entry::getKey, value -> value.getValue ().toString ()));
}
```

If this is already possible, then please let me know. I may have overlooked something in the library/code
Thanks!

**Comment by wnameless** [comment]
It is not possible for now. However the solution you provided in the post is pretty efficiency in the performance of Java. I prefer the way you handle this problem right now rather than modify any internal code of my library.
