### ISSUE TITLE
能按照json array排序吗？

### ISSUE THREAD

**Issue by legolas007** [wnameless/json-flattener#64]

**Comment by legolas007** [comment]
能够指定key给json排序，默认字典序等

**Comment by legolas007** [comment]
Can you sort JSON array by key?

**Comment by wnameless** [comment]
No, the key sorting feature is not a part of this library. However JsonFlattener can produce a flattened Java Map, you can sort keys easily by following approach:
`new TreeMap(flattenedMap);`

After doing this, you can convert the new TreeMap to a JSON string by Jackson or GSON .
