### ISSUE TITLE
Create API for flattening / unflattening JSON from Map<String, Object>

### ISSUE THREAD

**Issue by evgenivanovi** [wnameless/json-flattener#66]
**Create API for flattening / unflattening JSON from Map<String, Object>.** The value of Map is either Map<String, Object> or just Object.

_Sorry for examples in Kotlin_

```kotlin
fun flattenJsonAsMap(source: Map<String, Any>): Map<String, Any> {
        return JsonFlattener(JacksonJsonCore(ObjectMapper()), source)
            .flattenAsMap()
}
    
fun unflattenJsonAsMap(source: Map<String, Any>): Map<String, Any> {
        return JsonUnflattener(JacksonJsonCore(ObjectMapper()), source)
            .unflattenAsMap()
}
```

**Comment by wnameless** [comment]
The json-flattener is based on the [json-base](https://github.com/wnameless/json-base) library which includes the JsonCore API. The JsonCore allows users to use any JSON implementation they like within the json-flattener and I treat it as an important feature.

Even though the default JSON implementation used in json-flattener is Jackson which can easily serialize any Java object, there are more lightweight JSON implementations which only focus on JSON strings.

I would like let users choose what is best for their needs, so I kept the exposed APIs of json-flattener in a simple way.
