### ISSUE TITLE
error for JsonValuesBase not found

### ISSUE THREAD

**Issue by avico78** [wnameless/json-flattener#67]
I guess it might a stupid one but can't figure it out ,
new to java so please excuse ....

I download Jar:json-flattener-0.13.0.jar
Trying running the example as:
```
import com.github.wnameless.json.flattener.JsonFlattener;
import com.github.wnameless.json.unflattener.JsonUnflattener;

....

String json = "{ \"a\" : { \"b\" : 1, \"c\": null, \"d\": [false, true] }, \"e\": \"f\", \"g\":2.3 }";
Map<String, Object> flattenJson = JsonFlattener.flattenAsMap(json);

```

Getting:
```
class file for com.github.wnameless.json.base.JsonValuesBase not found


```

**Comment by wnameless** [comment]
You are losing some of the dependencies. Try to use an IDE to run your example instead of pure command-lines. Any modern IDE, which supports Maven or Gradle, can do this job very well.
