### ISSUE TITLE
JsonFlattener unflatten method taking high CPU and memory utilization due to high Pattern objects and compile.

### ISSUE THREAD

**Issue by vsachinv** [wnameless/json-flattener#79]
Hi,

We are facing performance challenges due to unflatten method slow and pattern compilation taking high cpu/memory as well when multiple JSON's getting unflatten in parallel. We are using 0.6 version. We are doing some json data changes after doing flatten and then unflattening the same.

```
Migration-Pool-Thread-9654
com.eclipsesource.json.JsonObject.get(JsonObject.java:560)
com.github.wnameless.json.unflattener.JsonUnflattener.unflatten(JsonUnflattener.java:250)
com.github.wnameless.json.unflattener.JsonUnflattener.unflatten(JsonUnflattener.java:58]
com.github.wnameless.json.unflattener.JsonUnflattener$unflatten.call(Unknown Source)
```
Is there any such known issue there?

**Comment by wnameless** [comment]
The 0.6 version is quite old. Why don't you try to use the newest version? Any difficulty here?
The 0.6 version is still using the minimal-json as the core JSON implementation, however this library is outdated somehow.
After 0.12 version, you are willing to choose any major Json Implementation you prefer.

**Comment by wnameless** [comment]
I just reviewed JsonUnflattener and found the pattern compilation problem you mentioned. I gave it a quick patch and released a new version of 0.16.4. You may take a try.

**Comment by vsachinv** [comment]
@wnameless Sure thanks. Let me try and get back to you.

**Comment by wnameless** [comment]
@vsachinv How is everything?

**Comment by vsachinv** [comment]
> @vsachinv How is everything?

Hi @wnameless 

Yes, After upgrade there is alot performance improvement in memory utilization but CPU is still high but lower than previous. I am checking further what could be the reason. Thanks for the fix. It helped.
