### ISSUE TITLE
Is it the intended behavior of the constructor JsonFlattener(JsonCore<?> jsonCore, JsonValueBase<?> json) to turn json into a string and then parse it?

### ISSUE THREAD

**Issue by HubCodes** [wnameless/json-flattener#85]
```java
  public JsonFlattener(JsonCore<?> jsonCore, JsonValueBase<?> json) {
    this.jsonCore = notNull(jsonCore);
    source = jsonCore.parse(json.toJson());
  }
```

Version 0.16.6 of this library has a constructor that takes a JsonCore and a JsonValueBase, stringify out the JsonValueBase, and then parses it.
Is this intended behavior? I believe that JsonValueBase is an abstraction layer and should not need to be parsed (just assign it to a class member).

**Comment by wnameless** [comment]
It is a typo. I am glad that you pointed it out for me. Thanks. It will be fixed on next iteration.

**Comment by wnameless** [comment]
There's a reason for that. As you can observe, jsonCore only operates when JsonFlattener is being initialized. If you don't need the provided JsonValueBase to be parsed again, simply provide JsonValueBase without jsonCore. However, the provided jsonCore can perform various operations depending on your backing JSON library. For instance, you might want to remove all trailing zeros from numbers.
