### ISSUE TITLE
Redundant initialisation of JacksonJsonCore instance and along with it ObjectMapper instance

### ISSUE THREAD

**Issue by deepakmishra** [wnameless/json-flattener#88]
When the JsonFlattener instance is created with JsonValueBase, then the initialisation of JacksonJsonCore in the constructor is redundant. It creates a new ObjectMapper instance inside it, which is huge in itself and consumes around 500 nanoseconds to 2000 nanoseconds to do so. The constructor can be simplified by removing the line in the link or making the JacksonJsonCore or ObjectMapper instance singleton. The instance variable `jsonCore` is not used anywhere in that flow as well.

https://github.com/wnameless/json-flattener/blob/8089ab83c1c0adafdde3ea4fa1975854ad483426/src/main/java/com/github/wnameless/json/flattener/JsonFlattener.java#L146

My use case needs parsing the value field in the JSON string again and passing the separator to the flattener. So I wrote a wrapper as below. Please guide me in this case. Could you remove the JacksonJsonCore initialisation in the JsonFlattener constructor?

```java
  public static Map < String, Object > flattenAsMap(String json) {
      JacksonJsonValue source = jsonCore.parse(json);
      if (source.isObject()) {
          JacksonJsonObject sourceObject = source.asObject();
          JacksonJsonValue valueObject = sourceObject.get("value");
          if (valueObject != null && valueObject.isString()) {
              sourceObject.set("value", jsonCore.parse(valueObject.asString()));
          }
      }

      com.github.wnameless.json.flattener.JsonFlattener jsonFlattener =
          new com.github.wnameless.json.flattener.JsonFlattener(source).withSeparator(SEPARATOR);
      return jsonFlattener.flattenAsMap();
  }
```

**Comment by wnameless** [comment]
The fastest way you can avoid this problem is that providing your own JacksonJsonCore, here is the example:

```java
var yourMapper = new ObjectMapper();
var jsonCore = new JacksonJsonCore(yourMapper);
String json = "{...yourJsonData...}";
var jf = new JsonFlattener(jsonCore, json);
```

**Comment by wnameless** [comment]
Since v0.17.0, the ObjectMapper in JacksonJsonCore is lazy-loading.

**Comment by deepakmishra** [comment]
In my use case, I have to do json parsing outside the constructor as we
have the logic of parsing the value separately. If I parse and pass the
string from outside, parsing the json twice will be slow.

My request was if the json is already parsed then why initialise jsonCore.
For now I have copied the whole class locally and removed that line.

**Comment by wnameless** [comment]
What is the version you are using now? The line you mentioned no longer exists.

**Comment by deepakmishra** [comment]
Yes. Now I can see the commit in master in May. How come I did not see those changes in August?  

https://github.com/wnameless/json-flattener/commit/95bb9ef64ac33d7f404e836754d8bb247c81e5dd#diff-b996671b728f92498030e86c139465ca18b3ac373d0b5a5272da5d519179bf39L146
