### ISSUE TITLE
custom separator option?

### ISSUE THREAD

**Issue by glebsts** [wnameless/json-flattener#9]
Hello,
thnx for nice lib.
I'm using json flattening in Ruby and Java projects so that both could provide same-looking json for elasticsearch. dot-separator is a bad idea for us and ELK, in ruby gem flat_keys there is an option to set custom separator, but this lib misses it. Can it be added please?
I'll try to make a pull request.

**Comment by wnameless** [comment]
I am working on the next version of JsonFlattener now. I would like to add this feature in. The new version should be released in couple days.

**Comment by glebsts** [comment]
Cool!
I actually have things working in my IDE now, I am adding unit tests. I assume there should be a set of disallowed separators, like quote.
Guess you don't need PR then?
If it will be released @Monday, would be awesome.

**Comment by wnameless** [comment]
The new version v0.2.0 has been released and there is a new separator configuration feature. Take a try.
